"""empty message

Revision ID: c31383a885b1
Revises: ba7b7d2ada48
Create Date: 2022-05-25 14:33:36.681033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c31383a885b1'
down_revision = 'ba7b7d2ada48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
