"""empty message

Revision ID: 01cb7d633452
Revises: 944520415355
Create Date: 2022-05-26 16:00:24.727966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01cb7d633452'
down_revision = '944520415355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_mime_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_mime_type')
    # ### end Alembic commands ###
