"""empty message

Revision ID: 2b840a3d7bb9
Revises: b2fbb974a20f
Create Date: 2022-05-27 12:09:51.642324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b840a3d7bb9'
down_revision = 'b2fbb974a20f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_data', sa.Column('user_id', sa.Integer(), nullable=False, comment='User ID'))
    op.create_index(op.f('ix_image_data_user_id'), 'image_data', ['user_id'], unique=False)
    op.create_foreign_key(None, 'image_data', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('image_data', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_data', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'image_data', type_='foreignkey')
    op.drop_index(op.f('ix_image_data_user_id'), table_name='image_data')
    op.drop_column('image_data', 'user_id')
    # ### end Alembic commands ###
