"""empty message

Revision ID: 5e684b5c4705
Revises: 2b840a3d7bb9
Create Date: 2022-05-27 13:25:50.681361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e684b5c4705'
down_revision = '2b840a3d7bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image')
    op.drop_column('users', 'image_mime_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_mime_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
