"""empty message

Revision ID: 6416ff4f33d7
Revises: 
Create Date: 2022-05-27 15:12:27.612486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6416ff4f33d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('lang', postgresql.ENUM('EN', 'RU', name='user_langs'), server_default='EN', nullable=False, comment='User lang'),
    sa.Column('role', postgresql.ENUM('Admin', 'User', name='user_roles'), server_default='User', nullable=False, comment='User roles'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_lang'), 'users', ['lang'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('image_data',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User ID'),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('image_mime_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    op.create_index(op.f('ix_image_data_user_id'), 'image_data', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_data_user_id'), table_name='image_data')
    op.drop_table('image_data')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_lang'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
