"""empty message

Revision ID: 688c40a76df2
Revises: 6416ff4f33d7
Create Date: 2022-05-30 12:31:42.188262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688c40a76df2'
down_revision = '6416ff4f33d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_data', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_data', 'id')
    # ### end Alembic commands ###
