"""empty message

Revision ID: 6c55af53ec8f
Revises: 
Create Date: 2022-05-26 15:44:58.391483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c55af53ec8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('lang', postgresql.ENUM('EN', 'RU', name='user_langs'), server_default='EN', nullable=False, comment='User lang'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_lang'), 'users', ['lang'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_lang'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
