"""empty message

Revision ID: 7e060784d63b
Revises: c31383a885b1
Create Date: 2022-05-25 15:45:41.765261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e060784d63b'
down_revision = 'c31383a885b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
