"""empty message

Revision ID: 944520415355
Revises: 6c55af53ec8f
Create Date: 2022-05-26 15:54:06.389892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944520415355'
down_revision = '6c55af53ec8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
