"""empty message

Revision ID: 9b391aac8ab5
Revises: b879f67aca1a
Create Date: 2022-06-06 12:12:52.238726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b391aac8ab5'
down_revision = 'b879f67aca1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
