"""empty message

Revision ID: b879f67aca1a
Revises: a17bc6bce524
Create Date: 2022-06-06 11:43:01.441215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b879f67aca1a'
down_revision = 'a17bc6bce524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
