"""empty message

Revision ID: ba7b7d2ada48
Revises: 0a6cc18c0c9c
Create Date: 2022-05-25 14:24:53.339123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7b7d2ada48'
down_revision = '0a6cc18c0c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'lang',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment='User lang')
    op.create_index(op.f('ix_users_lang'), 'users', ['lang'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_lang'), table_name='users')
    op.alter_column('users', 'lang',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment=None,
               existing_comment='User lang')
    # ### end Alembic commands ###
